import type { Category } from '../types'

export const CATEGORIES: Category[] = [
  { id: 'guilty-pleasure', name: 'My Guilty Pleasure' },
  { id: 'all-time-favourite', name: 'My All-Time Favourite' },
  { id: 'teenage-years', name: 'A Song From My Teenage Years' },
  { id: 'nobody-expects', name: 'A Song Nobody Expects Me to Like' },
  { id: 'karaoke-song', name: 'My Karaoke Song' },
  { id: 'describes-me', name: 'A Song That Describes Me' },
  { id: 'gets-me-going', name: 'A Song That Gets Me Going' },
  { id: 'party-starter', name: 'The Perfect Party Starter' },
  { id: 'road-trip', name: 'The Ultimate Road Trip Song' },
  { id: 'closing-song', name: 'The Perfect Closing Song' },
  { id: 'best-90s', name: 'The Best Song From the 90s' },
  { id: 'best-icelandic', name: 'The Best Icelandic Song' },
  { id: 'underrated', name: 'An Underrated Masterpiece' },
  { id: 'describes-someone', name: 'A Song That Describes Someone Here' },
  { id: 'main-character', name: 'My Main Character Song' },
  { id: 'impossible-to-escape', name: 'A Song That Was Impossible to Escape' },
  { id: 'defines-this-generation', name: 'A Song That Defines This Generation' },
  { id: 'rent-free', name: 'A Song That Lives Rent-Free in My Head' },
  { id: 'actually-overrated', name: 'A Song That Is Actually Overrated' },
  { id: 'everyone-hates-i-love', name: 'A Song Everyone Hates but I Love' },
  { id: 'everyone-loves-i-hate', name: 'A Song Everyone Loves but I Hate' },
  { id: 'artist-ill-defend', name: "An Artist I'll Defend Forever" },
  { id: 'didnt-deserve-to-flop', name: "A Song That Didn't Deserve to Flop" },
  { id: 'aged-well', name: 'A Song That Aged Surprisingly Well' },
  { id: 'aged-badly', name: 'A Song That Aged Badly' },
  { id: 'embarrassed-every-word', name: "A Song I'm Embarrassed to Know Every Word To" },
  { id: 'hear-first-time-again', name: 'A Song I Wish I Could Hear Again for the First Time' },
  { id: 'no-right-being-this-good', name: 'A Song That Has No Right Being This Good' },
  { id: 'recently-rediscovered', name: 'A Song I Recently Rediscovered' },
  { id: 'took-time-to-grow', name: 'A Song That Took Time to Grow on Me' },
  { id: 'never-get-tired-of', name: 'A Song I Never Get Tired Of' },
  { id: 'during-the-apocalypse', name: 'A Song to Play During the Apocalypse' },
  { id: 'confuse-everyone-party', name: 'A Song to Confuse Everyone at a Party' },
  { id: 'worst-wedding-song', name: 'The Worst Possible Wedding Song' },
  { id: 'would-ruin-the-mood', name: 'A Song That Would Ruin the Mood' },
  { id: 'minor-crime-soundtrack', name: 'A Song to Play While Committing a Minor Crime' },
  { id: 'matches-my-delusion', name: 'A Song That Matches My Delusion' },
  { id: 'questionable-decisions', name: 'A Song for Making Questionable Decisions' },
  { id: 'describes-friend-group', name: 'A Song That Describes This Friend Group' },
  { id: 'wake-me-from-a-coma', name: 'A Song That Would Wake Me From a Coma' },
  { id: 'biggest-red-flag', name: 'My Biggest Red-Flag Song' },
  { id: 'celebrity-song', name: 'A Surprisingly Good Celebrity Song' },
  { id: 'fave-another-country', name: 'My Favourite Song From Another Country' },
  { id: 'fave-past-decade', name: 'My Favourite Song From a Past Decade' },
  { id: 'fave-another-language', name: 'My Favourite Song in Another Language' },
  { id: 'fave-from-a-movie', name: 'My Favourite Song From a Movie' },
  { id: 'fave-solo-artist', name: 'My Favourite Song by a Solo Artist' },
  { id: 'fave-single-year', name: 'My Favourite Song From a Single Year' },
]

// Notað til að fylla sjálfkrafa út lög fyrir gervi-leikmenn sem "hafa ekki skilað" ennþá.
// Fyrstu tveir færslurnar eru vísvitandi eins til að hægt sé að prófa Great Minds bónusinn.
export const MOCK_SONG_POOL: { title: string; artist: string }[] = [
  { title: 'Dancing Queen', artist: 'ABBA' },
  { title: 'Dancing Queen', artist: 'ABBA' },
  { title: 'Ísland', artist: 'Bubbi Morthens' },
  { title: 'Blinding Lights', artist: 'The Weeknd' },
]
